# yaml-language-server: $schema=https://json.schemastore.org/yamllint.json

# Configuration
template: formal.html
use_photo: false
photo: photo.png
use_favicon: false
favicon: favicon.ico
pdf_generation: true
pdf_name: emiliano-contreras.pdf

# Metadata
name: Emiliano Contreras
title: Mechatronics Engineering Student
resume_link: "0xemiss.github.io"
facts:
  - title: Residence
    url: https://maps.app.goo.gl/JQh1aeYKJ3wsEVZq9
    icon: <i class="fa fa-home fact-icon"></i>
    text: Hermosillo, Sonora, Mexico
  - title: Phone
    url: tel:+526624116118
    icon: <i class="fa fa-phone fact-icon"></i>
    text: (662) 411-6118
  - title: Email
    url: mailto:emilianocontrerasr03@gmail.com
    icon: <i class="fa fa-envelope fact-icon"></i>
    text: emilianocontrerasr03@gmail.com

jobs:
  - position: Participant
    period: 2025
    company: E3 Semiconductors UNISON Program
    bullet_points:
      - Learned about the semiconductor industry and its applications.
      - Strengthened ethical awareness and social responsibility.
    technology:
      - Semiconductor fundamentals
      - Industry practices
      - CSR

  - position: Trainee
    period: 2024
    company: Santander Agile Program
    bullet_points:
      - Learned agile methodology principles.
      - Worked in teams following agile workflows.
    technology:
      - Agile
      - Team collaboration

educations:
  - degree: Mechatronics Engineering
    period: Expected May 2028
    university: Universidad de Sonora

  - degree:
    period: 2026-2
    university: International Exchange at Politechnika Łódzka, Poland

    projects:
      - title: Adjustable DC Power Supply
        skills: ['Wave rectifier', 'Power Circuits', 'Filter π']
        contents: Hands-on design and implementation of an adjustable DC power supply.
      - title: SCARA Robotic Arm
        skills: ['Mechanisms', 'Robotic', 'Control']
        contents: Design and construction of a SCARA-type robotic arm prototype.
      - title: Humidity and Temperature Monitoring System
        skills: ['Docker', 'Node-Red', 'MySQL', 'Chat-bot']
        contents:  Hands-on design and implementation of the system, featuring network communication between two microcontrollers and database access via Telegram.
    # relevant_courses: Mathematics, Electronic Circuits, Programming, Mechanisms, Control Systems.

personal_projects:
  - title: Prototypes and Competitions
    period: 2023 - Present
    description: Hands-on learning through practical prototypes and participation in engineering competitions, including the 3rd MAKERSPACE EXPO.
    skills: ['Prototyping', 'Functionality', 'Electrical Design']

skills:
  - Excellent communication and teamwork skills.
  - Strong sense of responsibility and kindness.
  - Motivated to encourage group performance.
  - Ability to learn quickly and adapt.

tech_skills:
  - title: Manufacturing Processes
    text: Welding, turning, milling machine, temporary mold casting, polymers.
  - title: Electronics
    text: Electronic symbols, low-pass and high-pass filters, amplifiers, logic gates, flip-flops, wave rectifiers.
  - title: Programming
    text: Python, C, Java.
  - title: Mechanics
    text: Design of mechanical elements and mechanisms.
  - title: Control
    text: Basic knowledge of block diagrams and control systems.
  - title: Software
    text: Python, Google Colab, NetBeans, Livewire, SolidWorks, Docker, Arduino, FluidSIM.
#  - title: Languages
#    text: Spanish, English.
